site_name: ReqSnake documentation & requirements

strict: true

nav:
  - Overview: README.md
  - MkDocs Integration: REQ-INTEGRATION.md
  - Markdown Parser: REQ-PARSER.md
  - Output Formats: REQ-OUTPUT.md
  - Testing: REQ-TEST.md

theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
plugins:
  - reqsnake
  - search

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
